### ISSUE TITLE
va branch build error 

### ISSUE THREAD

**Issue by davephillips** [squinkylabs/SquinkyVCV#11]
g++  -Wsuggest-override -std=c++11 -I./dsp/generators -I./dsp/utils -I./dsp/filters -I./dsp/third-party/falco -I./composites -fPIC -I../../include -I../../dep/include -DSLUG=squinkylabs-plug1 -DVERSION=0.6.0dev  -MMD -MP -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_LIN -c -o build/src/VocalFilterModule.cpp.o src/VocalFilterModule.cpp
src/VocalFilterModule.cpp:25:53: error: declaration of ‘using VocalFilter = class VocalFilter<WidgetComposite>’ [-fpermissive]
     using VocalFilter = VocalFilter<WidgetComposite>;
                                                     ^
In file included from src/VocalFilterModule.cpp:6:0:
./composites/VocalFilter.h:14:7: error: changes meaning of ‘VocalFilter’ from ‘class VocalFilter<WidgetComposite>’ [-fpermissive]
 class VocalFilter : public TBase
       ^
../../compile.mk:57: recipe for target 'build/src/VocalFilterModule.cpp.o' failed
make: *** [build/src/VocalFilterModule.cpp.o] Error 1
[dlphilp@The6300 squinky-va]$ git branch
  master
* vocal-animator

**Comment by squinkylabs** [comment]
Cool – I’ll take a look.

**Comment by squinkylabs** [comment]
oops, forgot to close this. I believe it's been fixed for a while.
