### ISSUE TITLE
Seq++ stretching a note off screen disappears on subsequent screens

### ISSUE THREAD

**Issue by campbellcreswick** [squinkylabs/SquinkyVCV#112]
Hi, if I stretch a note off screen it disappears on the next 2 bar screen. The note still plays but is not visible. Regards

**Comment by squinkylabs** [comment]
Yes, this is a known limitation. We hope to fix or improve this situation.

**Comment by squinkylabs** [comment]
It is much improved in 1.0.5, although still possible if the note is many bars long.

**Comment by campbellcreswick** [comment]
Thank you so much, it now works very well for me.

Regards Campbell
