### ISSUE TITLE
Form mixer volume control range seems odd

### ISSUE THREAD

**Issue by KarateSnoopy** [squinkylabs/SquinkyVCV#116]
Checkout this setup.  When I route 1.0 in, I get 1.4 out?

![p1](https://user-images.githubusercontent.com/7510226/66714186-837e8780-ed68-11e9-95a8-a9ec290b9da8.PNG)

If I set the master volume to default (of 0.75), I get 0.709 out?  Seems odd

![p2](https://user-images.githubusercontent.com/7510226/66714187-837e8780-ed68-11e9-968c-9c07aaa956c0.PNG)

AS mixer is more logical.  I turn it up to max volume, I get the same output level as the input level as seen here:
![p3](https://user-images.githubusercontent.com/7510226/66714217-01db2980-ed69-11e9-925d-507155958793.PNG)

**Comment by squinkylabs** [comment]
Yes, in the default position the master volume has 0db gain, but if you turn it up it has (iirc) +6db gain. The intention is that users find it useful to be able to boost volume a little if they want to.
