### ISSUE TITLE
seq++: often can't change snap settings in right click menu

### ISSUE THREAD

**Issue by ROGAVKA** [squinkylabs/SquinkyVCV#119]
Hi,

when I want to change "Snap to grid" or "Snap duration to grid" setting I open right click menu and click on these settings. 19 times out of 20 nothing happens: tick stays on/off. Now once in a while it works and setting is actually changed. Other items in the menu work fine, but the whole behaviour of this menu is strange, sometimes it closes after setting change and sometimes not. 

I'm on Windows 10. Guess I could record the problem if it could help. Meanwhile, there aren't any keyboard shortcuts for snap options, right?

**Comment by ROGAVKA** [comment]
Ok, so today I understood that settings actually change, but the tick next to it doesn't appear/disappear on the click, and the menu stays open, so I got full impression that it doesn't change. If i click on a setting, close the menu and open it again the tick is displayed correctly. So it's only menu view bug.

**Comment by squinkylabs** [comment]
There is a bug that causes the menu to not go away immediately, and that is probably causing this strange behavior. What's actually happening is that there are two copies of the menu on top of each other.

Assuming it's the same cause, this will be fixed in the next version.

**Comment by ROGAVKA** [comment]
Makes sense, so when I click on the setting the top menu is closed but i still see the bottom one without setting change. Thanks!

**Comment by squinkylabs** [comment]
fixed in 1.0.6
