### ISSUE TITLE
Ev3 shows info when hover over waveform in right hand bottom corner of rack

### ISSUE THREAD

**Issue by Petervos2018** [squinkylabs/SquinkyVCV#120]
When using tooltips. Even in between the cv inputs and outputs, and even the bottom screws ;)
I mean over there : 

![EVE info](https://user-images.githubusercontent.com/46076474/68422757-16acb080-01a1-11ea-928f-9d2bd97052ff.png)

Greetings Peter.

**Comment by squinkylabs** [comment]
Interesting. I don't get tooltips at all on that control. tx.

**Comment by Petervos2018** [comment]
> 
> 
> Interesting. I don't get tooltips at all on that control. tx.

You do, but it's in right hand bottom corner of rack

**Comment by squinkylabs** [comment]
No, you do, but I don't. I saw your included image. But that doesn't happen to me.

**Comment by Petervos2018** [comment]
Ooh I'm special...
