### ISSUE TITLE
Volume difference ExTwo

### ISSUE THREAD

**Issue by alasdairmoons** [squinkylabs/SquinkyVCV#122]
Hi all, 

ExTwo is a bit quieter than when connecting a stereo singal into two panned inputs of Ex4 or Form.
At least on my Linux Mint 19.1

**Comment by squinkylabs** [comment]
It's intentional so that a mono signal into a mono channel will be the same perceived volume as a stereo signal into a stereo channel. It's a 3db difference.

**Comment by alasdairmoons** [comment]
Ah, o.k. thanks
