### ISSUE TITLE
Octaves in Seq++ loading from midi file

### ISSUE THREAD

**Issue by ajbmorris** [squinkylabs/SquinkyVCV#123]
Seq++ seems to be loading midi files one octave too high? I transcribed the midi file in anthemscore and double checked in midi editor - both load the file with the bottom note at C4, but Seq++ seems to be opening the same thing at C5....
[09 Reunion precussion.zip](https://github.com/squinkylabs/SquinkyVCV/files/3826098/09.Reunion.precussion.zip)

**Comment by squinkylabs** [comment]
Interesting. Will take a look.

**Comment by ajbmorris** [comment]
Also noticed that  the midi end of file is inconsistent - seems to be defined by the last note rather than the end of the midi sequence if that makes sense - causes problems when trying to synch looping etc

**Comment by squinkylabs** [comment]
Interesting. I modified the open source midi file reader to look at the end event. Do you have a simple example you could post that shows this issue?

**Comment by ajbmorris** [comment]
I'll have to check - I ended up fixing it in later imports by inserting a dud note right at the end, but I think there's still a stray one in the patch I put on facebook

**Comment by squinkylabs** [comment]
Verified that the midi file import/export is indeed shifted by an octave. Do you have a file that will show the end-event issue?

**Comment by squinkylabs** [comment]
fixed in 1.0.6
