### ISSUE TITLE
Unable to compile anymore on Windows

### ISSUE THREAD

**Issue by caecos** [squinkylabs/SquinkyVCV#147]
per::genTableValues(const Spline&, int)':
dsp/utils/AsymWaveShaper.cpp:67:9: error: 'printf' was not declared in this scope
   67 |         printf("%ff", y);
      |         ^~~~~~
dsp/utils/AsymWaveShaper.cpp:3:1: note: 'printf' is defined in header '<cstdio>'; did you forget to '#include <cstdio>'?
    2 | #include "AsymWaveShaper.h"
  +++ |+#include <cstdio>
    3 |
dsp/utils/AsymWaveShaper.cpp: In static member function 'static void AsymWaveShaper::genTable(int, double)':
dsp/utils/AsymWaveShaper.cpp:81:5: error: 'printf' was not declared in this scope
   81 |     printf("float symmetry_table_%d[%d] = {\n", index, iNumPoints);
      |     ^~~~~~
dsp/utils/AsymWaveShaper.cpp:81:5: note: 'printf' is defined in header '<cstdio>'; did you forget to '#include <cstdio>'?
dsp/utils/AsymWaveShaper.cpp:87:5: error: 'fflush' was not declared in this scope
   87 |     fflush(stdout);
      |     ^~~~~~
make: *** [C:/msys64/Rack-SDK/compile.mk:69 : build/dsp/utils/AsymWaveShaper.cpp.o] Erreur 1

**Comment by caecos** [comment]
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\plugin.dll.EtPMRk.ltrans8.ltrans.o:<artificial>:(.rdata$.refptr._ZN13OnsetDetector9frameSizeE[.refptr._ZN13OnsetDetector9frameSizeE]+0x0): undefined reference to `OnsetDetector::frameSize'
collect2.exe: error: ld returned 1 exit status
make: *** [C:/msys64/Rack-SDK/compile.mk:59 : plugin.dll] Erreur 1

**Comment by squinkylabs** [comment]
I assume you are trying to build the master branch, correct?
Are you building using msys2 and just running `make`?
Could you tell me what version of gcc you are using? (type gcc --version)

**Comment by caecos** [comment]
I use MSYS2 and try to compile the ck-1 branch with make dist using the SDK...

Téléchargez Outlook pour iOS<https://aka.ms/o0ukef>
________________________________
De : squinkylabs <notifications@github.com>
Envoyé : Thursday, June 4, 2020 11:30:05 AM
À : squinkylabs/SquinkyVCV <SquinkyVCV@noreply.github.com>
Cc : caecos <caecos@hotmail.ca>; Author <author@noreply.github.com>
Objet : Re: [squinkylabs/SquinkyVCV] Unable to compile anymore on Windows (#147)


I assume you are trying to build the master branch, correct?
Are you building using msys2 and just running make?
Could you tell me what version of gcc you are using? (type gcc --version)

**Comment by squinkylabs** [comment]
ok, fixed now. thanks for your patience. please be aware that any experimental modules may change at any time, breaking any patches that may use them.
