### ISSUE TITLE
feature request: make Squinky Labs compatible/working with modular fungi lights off

### ISSUE THREAD

**Issue by smok-e** [squinkylabs/SquinkyVCV#150]
the title says it ;-)
to make it a bit more specific:
I would find it great when I could see the notes in seq++ shine through

and maybe it would be more appealing if the mute and solo buttons in Form have different colors.

I would like any knobs to shine through, and it would even be more intreresting if they would change 
the colors or the transparency of the color depending on their value. But I don't think this is easy to do.

**Comment by squinkylabs** [comment]
Ah ok, I thought that might be it. fwiw - it's difficult for the title to "say it" when we have about 20 modules ;-)

**Comment by squinkylabs** [comment]
Current compressors support lights out. I don't think having knobs glow is really in the spirit lights out, is it? Anyway, closing this since compressor does it.
