### ISSUE TITLE
Kitchen Sink: Problem with polyphony >4

### ISSUE THREAD

**Issue by anlexmatos** [squinkylabs/SquinkyVCV#156]
Using Kitchen Sink with MIDI-CV providing V/oct and Gate voltage, polyphony channels 5 and above are not playing the right notes.

To reproduce, use the following patch:

![image](https://user-images.githubusercontent.com/12039110/88345468-fcf1d000-cd13-11ea-9b79-17a519700515.png)

Ensure that Polyphony in MIDI-CV is set to 5 and the mode is set to Rotate.
Then play C->D->E->F->G (with QWERTY keyboard input that is Z->X->C->V->B).

What you will hear instead is C->D->E->F->D.

**Comment by squinkylabs** [comment]
Yes, I cans easily reproduce this issue. Wow - what a stupid bug. Tx for reporting. Will push out a fix soon

**Comment by squinkylabs** [comment]
fixed in 1.0.10
