### ISSUE TITLE
Windows binary (v0.6.2) here!

### ISSUE THREAD

**Issue by DomiKamu** [squinkylabs/SquinkyVCV#16]
Hi, this is the Windows binary, for release (v0.6.2) ;)
[squinkylabs-plug1-0.6.2-win.zip](https://github.com/squinkylabs/SquinkyVCV/files/1921200/squinkylabs-plug1-0.6.2-win.zip)

**Comment by squinkylabs** [comment]
0.6.2 binaries for all platforms are now in the plugin manager.

**Comment by squinkylabs** [comment]
closing, since 0.6.3 is now in the plugin manager.
