### ISSUE TITLE
EV3 Summed output doesn't

### ISSUE THREAD

**Issue by lamech** [squinkylabs/SquinkyVCV#174]
I can't get anything out of the summed output at the lower right of EV3.

It's not hard to add a little mixer next to it (or merge the three outputs into a polyphonic cable), but the summed/normalized output as documented is exactly what I want for e.g. [dubby minor triad saws](https://patchstorage.com/ronny-priess-dub-techno-stab-recipe-2/); it'd be so great if it worked!

**Comment by lamech** [comment]
<img width="1314" alt="Screen Shot 2020-10-18 at 9 52 55 PM" src="https://user-images.githubusercontent.com/27463/96393399-fa750a00-118c-11eb-9860-c2666362fe52.png">

[EV3 no summed output.vcv.gz](https://github.com/squinkylabs/SquinkyVCV/files/5398614/EV3.no.summed.output.vcv.gz)

Example patch attached. I can see I'm getting output from the individual VCO's, but nothing at the summed output port. Am I just using it wrong?

**Comment by squinkylabs** [comment]
Quoting from the manual:
```
The output section has a column of three output level controls, one for each VCO. Then there are the three jack, one for each VCO output, and a mixed output.
```
I can see from your screen shot that all three have their volume controls at zero. If you turn them up a bit you will hear something.

Sarcasm aside, the manual is a bit ambiguous about which outputs are affected by those volume controls. Sorry about that.

**Comment by squinkylabs** [comment]
And, yes, it will make it very easy to generate some triads ;-)

**Comment by lamech** [comment]
This is great news! User Error (esp when I'm the user) means I don't need to wait for you to release a fix ;)

Meanwhile it's interesting that I missed that. Those wee buttons aren't labelled and it's not clear that they act as a 3-channel mixer for the mixed output only. With your permission I might throw you a pull request for some documentation improvement around that. Cheers!

**Comment by squinkylabs** [comment]
sure, tx.

**Comment by lamech** [comment]
I see some commits bringing old doc improvements back, including the stuff about the 3-to-1 mixer etc. Thanks for taking care of this!
