### ISSUE TITLE
please redo the piano roll 

### ISSUE THREAD

**Issue by XtremeSounds** [squinkylabs/SquinkyVCV#175]
Im sorry but if you can please recreate this plugin with a more responsive piano roll like Fl studio has it will be be easier to work with.   

A few other features that would be good are using the mouse to scroll up and down the octave range as well as using the mous clicks to set the pattern length or perhaps knobs on the left to set that.

**Comment by squinkylabs** [comment]
Sorry, we don't have enough time to re-create FL studio as a free VCV module. Perhaps you could ask them to port FL studio to VCV?

**Comment by XtremeSounds** [comment]
Thats not what I meant, what I meant was can you fix your seq piano roll for midi notes to function more like the piano roll in fl studio
