### ISSUE TITLE
Seq++ doesn't load file

### ISSUE THREAD

**Issue by nnbveh** [squinkylabs/SquinkyVCV#177]
Hi. I've tried to load a short simple midi file but nothing shows up in the editor...

I'm on mac if that matters.

[beat.mid.zip](https://github.com/squinkylabs/SquinkyVCV/files/5470378/beat.mid.zip)

**Comment by squinkylabs** [comment]
It loads just fine for me, although the pitches are very low. maybe you didn't scroll far enough? The tab key is very hand for this. It will find the "next" not and scroll it into view.
![image](https://user-images.githubusercontent.com/16314838/97811065-ede0bf00-1c2c-11eb-8847-e2cf40ff51fe.png)

**Comment by nnbveh** [comment]
Ah, that must be it! Thanks!

**Comment by squinkylabs** [comment]
No problem. I didn't see it at first either. But when I saw that pink line indicating the end of track had moved I knew something was loaded.

Hope you enjoy the module.
