### ISSUE TITLE
[win] Latest update seems to have broken Rack in Windows

### ISSUE THREAD

**Issue by jamshark70** [squinkylabs/SquinkyVCV#178]
1. Squinky Labs updated today on my Windows machine.
2. Now, if I right-click to add a module, Rack crashes.
3. Move "squinkylabs-plug1" to another folder (outside of "plugins-v1").
4. Right-click no longer crashes.

So I believe something is broken in the last update.

**Comment by squinkylabs** [comment]
Yes. There are several thread about this on the community forum, and on Facebook. Definitely removing that plugin folder makes it stop crashing. I've posted a release here that works fine, is you absolutely must have your S-lab ;-)

The release is here: https://github.com/squinkylabs/SquinkyVCV/releases/tag/v1.0.14

Sorry about this confusion.

**Comment by SteveRussell33** [comment]
I don't know if this will be of any help. Using the release as downloaded from VCV library crashed my Win 10 machine. Yet if I compile the main branch myself with the latest GCC version (v10.2) the build works fine.

**Comment by barmario** [comment]
> Yes. There are several thread about this on the community forum, and on Facebook. Definitely removing that plugin folder makes it stop crashing. I've posted a release here that works fine, is you absolutely must have your S-lab ;-)
> 
> The release is here: https://github.com/squinkylabs/SquinkyVCV/releases/tag/v1.0.14
> 
> Sorry about this confusion.

Your release posted here works for me on windows 10, thank you!

**Comment by squinkylabs** [comment]
@SteveRussell33 yes, for sure it's the build that gets made on the build machine that's causing the issue. The code in Seq++ that's crashing is (I think) totally legit "C". I think I could code around this issue, but actually trying to fix it seems like the right thing to do. Anyway, won't know everything until this is fixed.

**Comment by squinkylabs** [comment]
it's been rolled back, so I'm closing this.
