### ISSUE TITLE
comp: entering values to controls does not work as expected

### ISSUE THREAD

**Issue by hexdump0815** [squinkylabs/SquinkyVCV#189]
hello,

first a big thank you for all those nice modules!

i just noticed a problem with comp (latest version from the library, linux): if i enter values via right click for the knobs they are not set to the proper value - as an example just right click and reenter the value displayed which should not create any change, but the knob will jump to another value then. affected are at least "thrsh", "att", "rel" and "mix" of comp, but no "out" on it. not sure if other modules are affected as well maybe (in case they share some code).

best wishes - hexdump

**Comment by squinkylabs** [comment]
ah, yes, you caught me. I confess I never implemented that. Will get to it next time!

**Comment by squinkylabs** [comment]
done now in version 1.0.19
