### ISSUE TITLE
Substitute just intonation

### ISSUE THREAD

**Issue by dbgrande** [squinkylabs/SquinkyVCV#200]
Since the just-intonation scales for Substitute and Submarine WK-101 are the same,
I expected that these quantizers would give similar values.

I set Substitute's VCO1 to square wave default level, while VCO2 and all the 
subharmonic levels were set to zero. (All other values were also kept at defaults.)

Then I used the following setups:

* Reftone -> Substitute -> Hot Tuna -> Specific Value

* Reftone -> WK-101 -> Specific Value

Using 12ET on both, I do get the same values\*\*, but when both quantizers are
set to just intonation, something seems off with Substitute's values:

|ratio|ref|sub(volts)|sub(note)|ratio|ref|wk(volts)|wk(note)|
---|---|---|---|---|---|---|---
|1/1|c4|0.0001|c4+0¢|1/1|c4|0.0000|c4+0¢|
|16/15|c#4|0.0670|c#4-19.61¢|16/15|c#4|0.0931|c#4+11.73¢|
|9/8|d4|0.1996|d4+39.54¢|9/8|d4|0.1699|d4+3.91¢|
|6/5|d#4|0.2505|d#4+0.55¢|6/5|d#4|0.2630|d#4+15.64¢|
|5/4|e4|0.3330|e4-0.45¢|5/4|e4|0.3219|e4-13.69¢|
|4/3|f4|0.4065|f4-12.16¢|4/3|f4|0.4150|f4-1.95¢|
|45/32|f#4|0.4995|f#4-0.56¢|45/32|f#4|0.4919|f#4-9.78¢|
|3/2|g4|0.6002|g4+20.20¢|3/2|g4|0.5850|g4+1.96¢|
|8/5|g#4|0.6663|g#4-0.44¢|8/5|g#4|0.6781|g#4+13.69¢|
|5/3|a4|0.8006|a#4-39.28¢|5/3|a4|0.7370|a4-15.64¢|
|9/5|a#4|0.8006|a#4-39.28¢|9/5|a#4|0.8480|a#4+17.60¢|
|15/8|b4|0.9994|c5-0.77¢|15/8|b4|0.9069|b4-11.73¢|
|2/1|c5|0.9994|c5-0.77¢|2/1|c5|1.0000|c5+0¢|

\*\* Ignoring sub-one-cent differences, and ignoring Specific Value's problem with 
octave values and slightly negative C notes: 0.9994V shows up as c4-0.77¢ instead of c5-0.77¢.

**Comment by squinkylabs** [comment]
Interesting. I'm no expert, but there are a couple of things I don't understand from your table. You show derivation from 12 ET for both, but I don't see where you show what is correct for Just Intonation. Perhaps it's in there, but I can't see it.

For example, I can see at 9/8 that D4 is different voltages, Sub is .1996, and sw is .1699. But what is the correct value? I'm quite willing to believe that Submarine of "correct" and I am "incorrect", but from the data I see above, it sounds like you are assuming that Submarine is correct. 

That said, looking at the internet it does seem that Submarine is closer to correct.

**Comment by squinkylabs** [comment]
ok, I fixed a typo that was messing things up with Just 12, and added some tests for that. commit is here: https://github.com/squinkylabs/SquinkyVCV/commit/600457aff2809235c4fafe7c26eced798105e4aa

feel free to pull down that branch and build it if you would like.

There is another issue when you move the input by semitones. There is some hysteresis in there to keep the output from being unstable. But I think there is too much hysteresis in the just modes, so when you input an ascending run of semitones (like in your test) it skips some, but hits them when you go down again. I think I should make some changes to avoid that effect, but I have not done that yet

**Comment by dbgrande** [comment]
All my values are read off from Specific Values, so are not completely accurate, and you're correct that
I'm using Hot Tuna to convert frequency to corresponding v/oct. To get precise voltage values, you'll have to use the log(ratio)/log(2) equation.

I tried your new commit, but the only difference I saw was with b4, which now gave: volts = 0.8752V and note = b4-49.78¢

However, then playing with REFTONE's FINE knob, I discovered that between c#4 and d4, there's an additional note with volts = 0.1254V & note = d4-49.53¢. It transitions at only -0.0001¢ down from d4, which is probably not a very good place to make a transition.

Maybe it would be helpful to add a temporary post-quantizer v/oct output for debug purposes?

**Comment by squinkylabs** [comment]
Ah, ok. Yes, I think the wierd transitions are related to the hysteresis. I don't think I need a debug output - this stuff is very easy to test in isolation. I just need to write some tests that mimic what you are doing and it the bugs should show their ugly head.

In general with bugs like this I prefer to write a test that shows the failure. It makes it much easier to fix, and also prevents future regressions.

**Comment by squinkylabs** [comment]
actually, looking in more detail, what the quantizer in Substitute does is take an input voltage, and quantize it to the nearest voltage to the scale in questions - in this case 12 note Just intonation. Apparently what the other quantizer does is first round to the nearest even tempered pitch, and then from there map to a pitch in the scale in question.

It's not entirely obvious to me which is "correct". I think they are just different.

**Comment by dbgrande** [comment]
In dsp/utils/SimpleQuantizer.cpp, if I change all the lines like:

	pitches_12just.insert(16.f / 15 - 1);

to

	pitches_12just.insert(log(16.f / 15)/log(2));

your Substitute's just outputs then match WK-101's just outputs.

However, I haven't looked at what happens to 8just or to rounding.

**Comment by squinkylabs** [comment]
That's interesting, and I will look into it. But off-hand that doesn't make any sense to me. The quantizer comes right at the V/Octave inputs, which as their name implies are exponential. There should be no need to do any log functions there. But I will look into it more when I have time.

**Comment by squinkylabs** [comment]
Sorry, been busy with other things. After a small amount of thought it's clear you are correct, and the tables should be logarithmic. I made some new tests that are less trivial, and all should be well. On "minor" issue came up that was vexing me. Some people use 16/15 for a minor second, and some people use 25/24. I assume you would prefer the 16/15 that (apparently) submarine uses (and that I had been attempting to use.

**Comment by dbgrande** [comment]
I'm sorry, but I don't know enough about just intonation to make that call.

However, I just learned last night that the C++11 standard library, which VCVRack is using, has a log2() function, so I should have been using:

	pitches_12just.insert(log2f(16.f / 15));

**Comment by squinkylabs** [comment]
This was fixed in release 1.0.16.
