### ISSUE TITLE
Rename Samp to "SFZ Player"

### ISSUE THREAD

**Issue by AndrewBelt** [squinkylabs/SquinkyVCV#205]
Since the panel says "SFZ Player", most users will want to search for this string in the VCV Library and module browser. You can simply change the "name" property to "SFZ Player".
Alternatively, you can add `"keywords": "sfz player"` which is supported by the VCV Library and VCV Rack v2.

**Comment by squinkylabs** [comment]
yes, this is pretty gross. and the link to the manual is wrong. will fix.

**Comment by squinkylabs** [comment]
thanks for reporting this, and thanks for putting up 1.0.17, which fixes this.
