### ISSUE TITLE
SFZ Player - ampeg_release not always working / noise issues

### ISSUE THREAD

**Issue by mosesve** [squinkylabs/SquinkyVCV#206]
Hi Squinky,

I already mentioned it in the forum and I have a reproducable issue, where even a seemingly fine sfz-file with global- or group-defined ampeg_release > 1 is producing the clicky noise, when a sample is cut off between zero-points.
I checked with sforzando in host and the same file is playing there without issues.

IvyAudio-PianoIn162-Close.sfz

https://ivyaudio.com/Piano-in-162

I am sorry, it is a big one, but just velovity-layers, no overlapping samples or note-off-samples.

**Comment by squinkylabs** [comment]
I just tried the Ivy piano with the version of SFZ Player that is in the VCV Library. I do not hear any clicking, and I can sure tell you that before I put in the release envelopes it clicked a lot, so I know this click you are talking about.

I think I was able to get it to click once out of perhaps 50 tries, but I could not get it to happen again.

Could you give me more info:
a) what is your polyphony set to (assuming you are playing it from a keyboard)?
b) is it a specific pitch, or all 88 pitches?
c) I assume by "cut off between zero points" you mean the sample is abruptly chopped off in mid-waveform, making a click?

**Comment by mosesve** [comment]
I did a little bit more digging into the issue, so that I can reproduce it always. I don't think it has anything to do with release, but with a new gate on the same channel and (maybe) same note. I attached a small patch (core, bogaudio, host) with the issue. At a certain tempo and gate-length the retriggering causes the first note to be instantly cut off and that seems to be the issue I am hearing. I put sforzando in host and even when I set the polyphony to 1 it does not have the issue. I think this issue will not appear when played via midi-cv and a high enough polyphony (rotating), but when sequenced via different sources it could occur  and that will often be the case within VCV.
But to answer your questions:
1. As i said, no keyboard but sequenced (for example harmonaig -> v/oct / Polygene + DGATE = Gate / S&H for Velocity)
2. all pitches
3. yes

I did not edit the K18, but the JazzFunkKit, which had no ampeg_release (so bad SFZ-File, not this issue).

[SFZ Player.zip](https://github.com/squinkylabs/SquinkyVCV/files/6305254/SFZ.Player.zip)

**Comment by squinkylabs** [comment]
Hmm, will have to look. Retriggering of ADSR when a voice is reassigned in an ancient controversy! I think I put two options in the Voyetra-8 back in the 80's....

Anyway, if you have one voice abruptly switch from one same to another I don't know if there is a good answer for what it should do. If it had a long attack then resetting the envelope to zero might (might) make sense, but since samples typically don't have a long attack.... I guess I should try to figure out what szorzando is doing.

**Comment by mosesve** [comment]
I just tested out other Samplers in VCV and almost all of them show the same behaviour, except the Lomas Sampler which can trigger at a much faster speed without any clicks. Maybe there is some voodoo in that module.

**Comment by squinkylabs** [comment]
I don't believe in voodoo. the ones that don't click must be fading out and then fading back in - inserting a bit of a delay and a fake out. I'll look into this, but it's not magic.

**Comment by squinkylabs** [comment]
I will be checking this out. Thanks for posting that patch!

**Comment by squinkylabs** [comment]
I convinced the SFZ spec people that 1ms is not the "real" default for SFZ - 30 is. Implemented that in 10.0.19
