### ISSUE TITLE
Right click in Seq++ note editor causes VCV to crash

### ISSUE THREAD

**Issue by cosmoproductions** [squinkylabs/SquinkyVCV#207]
[log.txt](https://github.com/squinkylabs/SquinkyVCV/files/6303414/log.txt)

G'day Squinky Labs!
Problem:
Right clicking anywhere in the note editor to bring up the pop up menu causes VCV to crash.

Notes:
I've just started using and learning the Seq++ sequencer.  When I was working with it yesterday I was able to right click in the note editor to bring up the menu and change its options.  Today, VCV crashes every time I right click in the note editor.  This bug is reproing 100% of the time, in the scripts from yesterday and in new scripts from today.  It seems to be since the most recent update to the modules but I'm not certain of the timing.  The attached log is from a file with nothing else in the patch but Seq++.

Workaround:
None that I've found.

Great tools!  Thank you

**Comment by squinkylabs** [comment]
Oh, right you are! Thanks. Ever since VCV updated their build process for the library these things keep popping up.

**Comment by cosmoproductions** [comment]
Correct, I'm using Windows 10 for Workstation.  Thanks for the quick response!

**Comment by squinkylabs** [comment]
this is pretty quick and dirty. I can't guarantee it won't crash somewhere else. But I can guarantee that it won't crash the same way!
[squinkylabs-plug1-1.0.16-win.zip](https://github.com/squinkylabs/SquinkyVCV/files/6308226/squinkylabs-plug1-1.0.16-win.zip)

**Comment by cosmoproductions** [comment]
Cool yeah that works. I won't worry about whether the fix crashes any of your other modules since I'm just working with Seq++ for now.  When you release this fix and an update to your modules is available in VCV Rack, it will overwrite this version that I've copied into the plugins directory correct?
Thanks again.

**Comment by squinkylabs** [comment]
Good! And that build was built with the same "rack toolchain" that they library uses, so the final one will work. Yes, I will be releasing version 1.0.17 to the library soon, and VCV will offer you an update whenever the library version is different from yours, so your red "update" light will turn on in VCV Rack.

**Comment by squinkylabs** [comment]
Fixed in 1.0.17, which is in the library now.
