### ISSUE TITLE
SFZ Player offset is ignored

### ISSUE THREAD

**Issue by coax75ohm** [squinkylabs/SquinkyVCV#212]
I'm trying to use an SFZ instrument that contains a substantial offset, 35k @48kHz, which is about 3/4 second that needs to be cut from the beginning of the samples. SFZ Player seems to ignore this value and plays the samples with the silent portion at the beginning.

The scope in this screenshot shows the gate and delayed audio signal:
![Screenshot (17)](https://user-images.githubusercontent.com/577587/117863758-bbf28a00-b259-11eb-9f1c-cca68cecefcb.png)

**Comment by squinkylabs** [comment]
Yes, you are correct. the current version does ignore offset. The manual actually documents this, I believe.

Is this a request that we add that? In general I have not seen many SFZ with a big offset like that. Is this an SFZ that I could download myself?

**Comment by coax75ohm** [comment]
The one with the big offset that I was trying to use is: https://www.pianobook.co.uk/library/church-steinway/

From running grep, I see it's also used in a fair number of others, though mostly for getting rid of pops and clicks. These are a couple of the more popular ones:
http://virtualplaying.com/virtual-playing-orchestra/
https://github.com/sfzinstruments/SplendidGrandPiano/

I guess this would be a feature request then (also the #define directive if it's not too much to ask, this is quite common as well).

**Comment by squinkylabs** [comment]
ok, I should be getting back to SFZ player soon, will implement some of these. pops and clicks with virtual playing orchestra doesn't sound good!

**Comment by coax75ohm** [comment]
Cool, I do understand the balance between supporting the entire spec and making it usable for a reasonable number of common sample packs.

After further examination of virtual playing orchestra, it seems mostly for time adjustment within a sample set (woodwinds use it the most); still a good reason to support it. Though beginning of sample noise removal is also a common use.

Anyway, huge thanks for making this module (some of the others aren't bad either ;)

**Comment by squinkylabs** [comment]
haha, thanks. I think I will put offset in the next version. It should be "easy".

**Comment by squinkylabs** [comment]
If you would be interested in testing, I have an experimental version that supports offset and looping (and some other stuff. Usually with testers I insist they have/get a Slack account (free). If you are interested, send me a PM via FB of VCV Community. Or, it we just want to build it you can do that any time, although the branch may move around. ATM its `par2`

**Comment by squinkylabs** [comment]
version in the library now has offset, end, and all the looping opcodes.
