### ISSUE TITLE
Feature Idea: Kitchen Sink FM/PM

### ISSUE THREAD

**Issue by mosesve** [squinkylabs/SquinkyVCV#214]
Hi, it's me again.

I've read a lot of stuff about FM in the last week, and I have two more ideas for the kitchen sink. Please don't see them as requests, but as ideas, and when these are not feasible, just close this issues.

A lot of VCOs in VCV have an FM-Input of some kind (linear, exponential, through-zero) if I am right. But I found just a few with phase modulation, which was the original modulation type in the DX7 as you will know. Most of them are totally unusable in a polyphonic context because they have an absurd CPU-usage amount. Or they have no features whatsoever in terms of an fm-operator (like feedback or ratios for example). I am wondering if this is because phase modulation is hard to implement or because it is just very CPU-hungry? 

So my idea would be to have an option on the kitchen sink to change the modulation type between frequency and phase modulation. 

Kind regards,

mo

**Comment by squinkylabs** [comment]
haha - let me quote the manual on this one:
```
A pedantic note about FM vs. PM
Most modules and synthesizers that claim to do "FM" really use phase modulation. Even the FX-7 used PM. The advantages of phase modulation of frequency modulation are:

PM Timbres stay the same as pitch is changed, whereas FM doesn't.
FM can easily go out of tune when heavy amounts of FM are applied. PM doesn't have this problem.
So we use phase modulation, as do most "FM" VCOs.
```

**Comment by squinkylabs** [comment]
btw, I haven't forgotten about the other suggestions - both very good.

**Comment by mosesve** [comment]
Oh! I should have read the manual more carefully! I was comparing the FM in the kitchen sink to that of drambo (an ipad app) which has both mod-types and thought it was FM, since it was more agressive than the phase-mod of that drambo osc... my bad, thank you for clarifying.

- mo

**Comment by squinkylabs** [comment]
No "bad" at all - tx for taking an interests. I'm not sure why Kitchen sink would wound more aggressive. I can guess plenty of things, but I have no idea. I do know how FM-OP works, and it should sound fairly similar to Kitchen Sink. At least the recent release that added oversampling to the FM inputs...
