### ISSUE TITLE
Need tester feedback for Thread Booster

### ISSUE THREAD

**Issue by squinkylabs** [squinkylabs/SquinkyVCV#22]
Feel free to open a new issue, or just add a comment to this one. Thanks!

**Comment by cmountvpr** [comment]
(OSX 10.8.5). Normally, whenever I navigate to Facebook while a VCV patch is running, the patch glitches *badly*, even a relatively simple one. The patch I used to test Thread Booster was pulling about 75% CPU, according to Activity Monitor. With the Booster set to Boost, there was no glitching. That's a good sign! Thanks! Tests will continue.

**Comment by cmountvpr** [comment]
From another user, Simon Bader...

The Thread Booster worked quite well. I noticed a significant improvement on my 2009 MacBookPro. It's got a Duo Core 2.54GHz processor and only 4GB of RAM, running OS 10.9.5. On the 13" display, I had about 3 rows of modules that pretty much filled the screen at 60/65% zoom.

**Comment by squinkylabs** [comment]
That's for the responses so far. @cmountvpr: we are unsurprised that booster helps in the app switching use case. Of course that's not a "primary use case" for VCV, but it is a little less annoying to not have the glitches when you app switch.
