### ISSUE TITLE
SFZ: Rack exit on load of "bad" SFZ

### ISSUE THREAD

**Issue by paulpiko** [squinkylabs/SquinkyVCV#223]
I loaded the Mellotron M300B sfz from Plogue_sforzatron_v1 after correcting the sample path. Rack exited to desktop, with no relevant entries in the log file. Upon investigation, I found there's a typo in the sfz for A#2, where it has tune-8 instead of tune=-8 (or tune=8?). After correcting the syntax it loads without issue.

**Comment by squinkylabs** [comment]
thanks for reporting that!

**Comment by squinkylabs** [comment]
Ok, there are a few bad things here. of course crashing is bad, but even if it didn't crash, it would display a very misleading error message. Here's the message it "should" show. Does that seem like acceptable behavior?

![image](https://user-images.githubusercontent.com/16314838/125545093-d7b32d54-fd55-4c26-8594-e33ff133db76.png)

That for from this sfz:
```sfz
// loop osc
<region>
oscillator=on
tune-8
sample=osc.wav
<region>
oscillator=on
sample=osc.wav
```

**Comment by paulpiko** [comment]
Looks good

**Comment by squinkylabs** [comment]
If you would be interested in trying to crash it with some intentionally mangled SFZ, you are invited. I can post windows or linux builds, and the code itself is on the `par3` branch in this github.

**Comment by paulpiko** [comment]
IIRC, I think I also crashed once trying to open an unmodified sforzatron.sfz. I can try that again if you have a Windows build I can download.

**Comment by squinkylabs** [comment]
I'll make one tonight.

**Comment by squinkylabs** [comment]
You can get it from here: https://github.com/squinkylabs/SquinkyVCV/releases/tag/stz-test-1

**Comment by paulpiko** [comment]
Trying the new build... Loading the sforzatron.sfz doesn't exit Rack anymore and displays an error message (I put the mapping with the missing = back). Narrowing down the error location is trickier because it has 10 includes; any chance of including the culprit file name in the error message?

**Comment by squinkylabs** [comment]
That is for sure a limitation - that the error collector doesn't keep track of the file it came from. Afraid that enhancement will have to wait until next time.

**Comment by squinkylabs** [comment]
fixed now in the library.
