### ISSUE TITLE
Comp II - Problem with Release Knob and Channel Selection

### ISSUE THREAD

**Issue by anlexmatos** [squinkylabs/SquinkyVCV#228]
Something odd is going on with the release knob when turning the channel knob. For example:

1. Initialize a Comp II module
2. Turn the Release Knob counter clockwise
3. Wiggle the Edit Channel knob back-and-forth more than once. Values change upon selecting a channel for the 2nd time

This seems to set the Release value for not just channel 1 but also 2-4, 7, and 8.

**Comment by squinkylabs** [comment]
I just tried it, and yes, it does seem like something very odd is going on. Is it just the release? I tried it quickly and at seems it is only release... Thanks for reporting this.

**Comment by squinkylabs** [comment]
oh, yeah, I see it's a very dumb bug. I'm going to be away for a couple of weeks, so I probably can't get a fix into the library immediately. If you would like a fix quickly I can post something or you can build it.

**Comment by squinkylabs** [comment]
In any case, fix is pushed to "main" now.

**Comment by squinkylabs** [comment]
fixed in 1.0.23

**Comment by anlexmatos** [comment]
Thanks!

**Comment by squinkylabs** [comment]
thanks for reporting it. It was a pretty bad bug!
