### ISSUE TITLE
EV3: Mixed Output isn't normalized

### ISSUE THREAD

**Issue by patman023** [squinkylabs/SquinkyVCV#47]
Depending on tuning, sync, and waveform interaction, the mixed output is hitting 30+V peak to peak (Fund>Scope)/+6dBFS (Bogaudio 3HP VU), without even patching any cv, which blows the voltage standard out of the water (https://vcvrack.com/manual/VoltageStandards.html#output-saturation). 

Obviously the easiest solution is to turn the waves down, but that's IMO not a feasible workaround, because that changes the blend of waves. 

Not sure exactly the coding that would have to happen to do this, and if it would affect aliasing, but one reference to go off of would be this bugfix: https://github.com/bogaudio/BogaudioModules/issues/14

**Comment by patman023** [comment]
[ev3notnormalized.txt](https://github.com/squinkylabs/SquinkyVCV/files/2551013/ev3notnormalized.txt)

**Comment by squinkylabs** [comment]
Interesting. On the other hand, if each VCO puts out 10v p-p (as most do), what should three mixed together do? They could all be turned down, as you say, and the blend would be the same, but then it would be impossible to turn any up to full level by itself. 

We just tried the same thing with fundamental modules. If you mix three VCOs together at full volume, a very high voltage comes out. 
![3x](https://user-images.githubusercontent.com/16314838/48045955-50d71280-e147-11e8-9fa0-b987aa3f4060.png)

**Comment by patman023** [comment]
The issue is that there will undoubtedly be hard digital clipping at some point downstream of the EV3, and it's going to sound as disgusting as... well, hard digital clipping.

**Comment by patman023** [comment]
[ev3notnormalized2.txt](https://github.com/squinkylabs/SquinkyVCV/files/2556963/ev3notnormalized2.txt)

**Comment by squinkylabs** [comment]
This will be in the next update.

**Comment by squinkylabs** [comment]
in version 0.6.14 (current version) the output is normalized. And the "+" icons turn green when this kicks in.
