### ISSUE TITLE
With four or more instances of LFN, output dies.

### ISSUE THREAD

**Issue by squinkylabs** [squinkylabs/SquinkyVCV#49]
With less than 4 instances it acts a little funny, but nothing easy to notice. But with six instance several would not output anything.

Affects version 6.0.10 and earlier versions (all current versions).

**Comment by jonheal** [comment]
With two instances, the first instance doesn't output anything upon reopening a patch.

**Comment by squinkylabs** [comment]
Thanks for the report. Yes, this issue seems like it can pop up any time there is more than one instance. Fix coming soon.

**Comment by squinkylabs** [comment]
Version 6.0.12 was submitted to the plugin-manager yesterday with this fix. Should show up in the next few days.

**Comment by squinkylabs** [comment]
Fixed since 0.6.12
