### ISSUE TITLE
Roland Juno 106

### ISSUE THREAD

**Issue by blackearth2014** [squinkylabs/SquinkyVCV#56]
Squinky Labs,

SAWS is the bomb and Thanks. I do have one request if possible. Is there a way or development to create a Juno 60/106 VCO Module?

https://greatsynthesizers.com/en/review/roland-juno-60-vintage-classic-with-lots-of-charme/

**Comment by squinkylabs** [comment]
oh, wow, that would be great. But don't know if we could pull that off.

**Comment by blackearth2014** [comment]
Okay cool but could you somehow emulate that famous chorus 1 and 2 effects.

As for the 106 VCO, I will see if I take two opposite PW Sqr waves from 2
functional VCO modules summed together into the waveShaper to take emulate
the sound via CV modulation from Chopper.

**Comment by squinkylabs** [comment]
will not be doing this.
