### ISSUE TITLE
Colors 0.6.14 background beat.

### ISSUE THREAD

**Issue by therealkitman** [squinkylabs/SquinkyVCV#61]
Hi,
If I use Colors with the default white noise setting 0db/oct, there is a distinct but consistent background beat or rhythm playing under the noise. I have stripped my patch down to just Colors and a mixer to audio output. No other white noise generator is doing this so it's not my setup. 
Most mysterious?
Regards,
Chris.

**Comment by squinkylabs** [comment]
Colors does work by generating a second or two of noise and playing it over and over, so this is certainly possible. Will have to investigate more closely to see if this is a result of a bug.

**Comment by therealkitman** [comment]
I have added a WAV file recorded on my system in this zip file. It's subtle but noticeable.
[20190307_101535_UqaVVW_monorecorder_SXlV4Pr0.zip](https://github.com/squinkylabs/SquinkyVCV/files/2939235/20190307_101535_UqaVVW_monorecorder_SXlV4Pr0.zip)

Also as a matter of side interest, Colors is by far the quietest of the noise generators and I need to 'pump up the volume' to hear it well enough for what I'm dabbling with. If you do think Colors needs some fixing maybe you can give it a bit of a boost too :)
![image](https://user-images.githubusercontent.com/14888092/53928266-6f80f200-40c4-11e9-9355-8374aa6eaf2e.png)

**Comment by squinkylabs** [comment]
yeah, we sometimes get the level wrong. Windows is telling me your zip file in invalid.

**Comment by squinkylabs** [comment]
but in any case, listening to Colors I can see what you are talking about. Unlikely to change that, as it's sort of inherent to this kind of noise generator. but for sure it's too quiet.

**Comment by therealkitman** [comment]
My zip was created under linux. I thought it would be cross platform compatible. Anyway, I have uploaded the WAV to my google drive https://drive.google.com/open?id=1_ehJlKMLSr0o3pA6N5ReygL2aahMxz24

**Comment by therealkitman** [comment]
> but in any case, listening to Colors I can see what you are talking about. Unlikely to change that, as it's sort of inherent to this kind of noise generator. but for sure it's too quiet.

wait, you mean you can hear the background beats or were you referring to the volume?

**Comment by squinkylabs** [comment]
Yes, just putting up an instance in isolation I can hear that it repeats. To my ears (which are not great) it's pretty subtle, but it is audible.

**Comment by VegaDeftwing** [comment]
I wonder if this could be made benefical in some way, maybe allow for setting the length of the noise sample to synchronize it with a clock or generate significantly more noise and loop when it hit's the end or when it's triggered to start over?

**Comment by Anthony-Lockwood** [comment]
This has been winding me up for weeks. I imagined various loops of voices and machinery clunking away in the background. The looping is almost exactly 1.5 sec. and does start to irritate, and for my purpose renders the module all but useless. It is a shame as was keen to use it as it is a little softer and easy going. Seems colors is the only noise module with this trait.
I even did some tests on an 11 second sample to observe and measure the looping and the frequencies envolved.
enclosed. 2 x spectrogram
All the best and thanks.
![Squinky white noise-sonic visualiser](https://user-images.githubusercontent.com/55862540/66067298-2c480e00-e543-11e9-8deb-e47ee59b9fff.png)
![Squinky white noise-audacity-](https://user-images.githubusercontent.com/55862540/66067303-2f42fe80-e543-11e9-9f83-46a4e873b149.PNG)

**Comment by squinkylabs** [comment]
Yes, as we noted, above, you are both correct, it does loop. We are sorry if this makes colors unusable for your application. Luckily there are many other noise generators for VCV, so it should be easy to find one that meets your needs.

**Comment by squinkylabs** [comment]
don't plan on changing this, so closing issue.
