### ISSUE TITLE
v1 component.hpp error

### ISSUE THREAD

**Issue by Coirt** [squinkylabs/SquinkyVCV#62]
In Squinky.hpp I get an error when trying to compile on windows. Should:

`
#ifdef __V1
#include "component.hpp"
#else
#include "componentlibrary.hpp"
#endif
`

be
`
#ifdef __V1
#include "componentlibrary.hpp"
#else
#include "component.hpp"
#endif
`

**Comment by squinkylabs** [comment]
Yes, unfortunately our "v1" branch is obsolete and no longer builds. The current v1 port is on the sq3b branch. We will update the readme to make it easier to find and build the v1 plugins.

**Comment by Coirt** [comment]
Cheers for the help!!! Greatly appreciated.
