### ISSUE TITLE
Won't compile on Windows 10 Pro

### ISSUE THREAD

**Issue by caecos** [squinkylabs/SquinkyVCV#63]
$ make
g++  -Wsuggest-override -std=c++11 -I./dsp/generators -I./dsp/utils -I./dsp/filters -I./dsp/third-party/falco -I./dsp/third-party/kiss_fft130  -I./dsp/third-party/kiss_fft130/tools -I./dsp/third-party/src -I./sqsrc/thread -I./dsp/fft -I./composites -I./sqsrc/noise -I./sqsrc/util -I./sqsrc/clock -I./sqsrc/grammar -I./sqsrc/delay -I./midi/model -I./midi/view -I./midi/controller -I./util -I./src/third-party -I.src/ctrl -D __V1 -DSLUG=squinkylabs-plug1 -fPIC -I../../include -I../../dep/include -DVERSION=0.6.14 -MMD -MP -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_WIN -D_USE_MATH_DEFINES -fmax-errors=5  -D NDEBUG -c -o build/src/LFNModule.cpp.o src/LFNModule.cpp
In file included from src/ctrl/SqMenuItem.h:6,
                 from src/LFNModule.cpp:5:
src/ctrl/SqUI.h:4:10: fatal error: widget/event.hpp: No such file or directory
 #include "widget/event.hpp"
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [../../compile.mk:65: build/src/LFNModule.cpp.o] Error 1

**Comment by squinkylabs** [comment]
Which branch our our repo are you trying to build? What version of VCVRack are you trying to build against?

We just verified that our `master` branch builds fine against VCVRack 0.6, as of today.

**Comment by caecos** [comment]
Hi,

Sq3b against 0.6.2c (rcomian version) all the others plugins compile fine. Yours also except for the last two update…

Marc


Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

________________________________
De : squinkylabs <notifications@github.com>
Envoyé : Sunday, March 10, 2019 4:09:51 PM
À : squinkylabs/SquinkyVCV
Cc : caecos; Author
Objet : Re: [squinkylabs/SquinkyVCV] Won't compile on Windows 10 Pro (#63)


Which branch our our repo are you trying to build? What version of VCVRack are you trying to build against?

We just verified that our master branch builds fine against VCVRack 0.6, as of today.

**Comment by squinkylabs** [comment]
yes, that branch is currently set up to compile against V1. If you would like to compile it against 0.6, you must edit a line of the `Makefile`
Find this:
```
# compile for V1 vs 0.6
FLAGS += -D __V1
```
and either remove or comment out that line that defined __V1

**Comment by caecos** [comment]
Ok thanks ...

Obtenez Outlook pour iOS<https://aka.ms/o0ukef>

________________________________
De : squinkylabs <notifications@github.com>
Envoyé : dimanche, mars 10, 2019 20:08
À : squinkylabs/SquinkyVCV
Cc : caecos; Author
Objet : Re: [squinkylabs/SquinkyVCV] Won't compile on Windows 10 Pro (#63)


yes, that branch is currently set up to compile against V1. If you would like to compile it against 0.6, you must edit a line of the Makefile
Find this:

# compile for V1 vs 0.6
FLAGS += -D __V1


and either remove or comment out that line that defined __V1

**Comment by caecos** [comment]
Works fine...

Obtenez Outlook pour iOS<https://aka.ms/o0ukef>

________________________________
De : Marc Demers <caecos@hotmail.ca>
Envoyé : dimanche, mars 10, 2019 21:05
À : squinkylabs/SquinkyVCV; squinkylabs/SquinkyVCV
Cc : Author
Objet : Re: [squinkylabs/SquinkyVCV] Won't compile on Windows 10 Pro (#63)

Ok thanks ...

Obtenez Outlook pour iOS<https://aka.ms/o0ukef>

________________________________
De : squinkylabs <notifications@github.com>
Envoyé : dimanche, mars 10, 2019 20:08
À : squinkylabs/SquinkyVCV
Cc : caecos; Author
Objet : Re: [squinkylabs/SquinkyVCV] Won't compile on Windows 10 Pro (#63)


yes, that branch is currently set up to compile against V1. If you would like to compile it against 0.6, you must edit a line of the Makefile
Find this:

# compile for V1 vs 0.6
FLAGS += -D __V1


and either remove or comment out that line that defined __V1
