### ISSUE TITLE
Saws, Shaper and EV3 react to mouse wheel button

### ISSUE THREAD

**Issue by Petervos2018** [squinkylabs/SquinkyVCV#66]
Hi,

The blue text on Saws, Shaper and EV3 can be modified by clicking with the mouse wheel button (also right button, but that's not really a problem).
I use the middle mouse button/wheel (click and hold) to move/drag the screen around in vcv. 
But when I accidentally click and hold on one of these modules I sometimes also change the settings f.e. turn a saw into a sine on saws or change AC to DC on Shaper.

Love your modules,
Greetings Peter

**Comment by squinkylabs** [comment]
Ah, yes, you are correct. Will fix this.

**Comment by Petervos2018** [comment]
Fixed in 0.6.15 Thank you Squinky ;)
