### ISSUE TITLE
v1 mixer8 onDrag enables M/S

### ISSUE THREAD

**Issue by Coirt** [squinkylabs/SquinkyVCV#68]
When dragging the level knob upon release it can enable the mute or solo depending on how far you drag on release of mouse down. Seems to be because the mouse coordinates are over the button.

![mix8SoloMuteOnDrag](https://user-images.githubusercontent.com/12150421/58259026-a5508100-7d6b-11e9-8a66-586bbdc132dd.gif)

**Comment by Coirt** [comment]
No problem... Aye, was a good guess.

**Comment by squinkylabs** [comment]
Should be fixed now.

**Comment by Coirt** [comment]
Okay, not tested but closing
