### ISSUE TITLE
vcv crashes/Mac

### ISSUE THREAD

**Issue by photodezijn** [squinkylabs/SquinkyVCV#7]
changin the range settings to exp crashes vcv on OS X
range setting are not saved. it always starts with 5hz

**Comment by Phal-anx** [comment]
similar on windows. it works fine as long as I dont connect a CV signal to the CV input in exp mode.

**Comment by squinkylabs** [comment]
Could we get some more reproduction info? Just tried on Windows and could not duplicate this. Will try OS X later.

Are these problems occurring with Rack 0.5.1?
Was this with downloaded release zip files, or built from source?
Does the crash happen immediately when switching to Exp? Or dies a CV need to be applied?

And btw, thanks to both of you for being the first bug reporters in our git issues!

**Comment by davephillips** [comment]
Hey Bruce,

The exp selection works fine until a CV input is added, then it crashes Rack with this error:

Rack: ./dsp/utils/LookupTable.h:42: static T LookupTable<T>::lookup(const LookupTableParams<T>&, T) [with T = float]: Assertion `input>=params.xMin && input<=params.xMax' failed.

The Range setting is saved between sessions, no problem here with that issue.

Rack (0.5.x) is built from source here, on Fedora 23 Linux. 

dp

**Comment by squinkylabs** [comment]
OK, I'll get that crashed fixed asap. can anyone shed more light in the inability to save ranges? Or was that only after a crash?

**Comment by squinkylabs** [comment]
Fixed in the source code (master). binaries in 11 or 12 hours.

**Comment by squinkylabs** [comment]
Both issues should be fixed in 0.5.1, which is now in our releases page, in the plugin manager, and on the master branch of the source code.
