### ISSUE TITLE
Feature Request: Stairway duplicate input when only L is connected

### ISSUE THREAD

**Issue by MarcBoule** [squinkylabs/SquinkyVCV#70]
Hi Bruce, in Stairway, when only the L input is connected, could it be possible to internally route it to the R input also? Cheers!

**Comment by squinkylabs** [comment]
But I have to wonder - just to save stacking two cables on the L output jack?

**Comment by MarcBoule** [comment]
Yes, although it appears trivial, it seems to be common practice and it can indeed be handy. I could name other modules that do this, but just take Chronoblob2 for instance. In its default state (dual delay), patching just the the L will automaticaly duplicate it to the R input.

But it should generally not be done both ways, only L -> R default when R is unplugged. In Chronoblob2, patching just to the R input is the recommended way to achieve ping pong delay (when setting the mode to ping pong of course). 

If for performance reasons you prefer to deactive the right channel when unused, then of course there are tradeoffs, but since I've seen many stereo modules do this, I was kind of expecting it when I patched into Stairway. Perhaps Omri, Espen, and others slack friends would have an opinion on this?

**Comment by squinkylabs** [comment]
No, that's fine. The jack is just sitting there, might as well make it do something. I would think this would apply the Shaper, too, which is now stereo.

And on these modules, why not have R -> L+R? It's either than or have the left output be dead in that case.

**Comment by MarcBoule** [comment]
Sure, in this case since there is no special feature for plugging R only, like in my Chronoblob2 example, so why not.

**Comment by squinkylabs** [comment]
done!
