### ISSUE TITLE
Pitch drift of Functional VCO

### ISSUE THREAD

**Issue by VegaDeftwing** [squinkylabs/SquinkyVCV#74]
Using VCO-1 and Functional VCO with the same v/oct source and fine tuning either until they match on a scope will result in a noticeable pitch drift over time.
![DeepinScreenshot_select-area_20190603001251](https://user-images.githubusercontent.com/11283620/58779281-0ca3d780-859b-11e9-93a6-43f81c1568be.png)
(my fundamental VCO-1 and Scope have a custom svg and ZZC's knobs on them, but no code changed)

**Comment by squinkylabs** [comment]
The ANLG feature of Fundamental VCO-1 includes a random fluctuation in pitch. Have you tried this with the dgtl/DIGI setting?

**Comment by VegaDeftwing** [comment]
And this is why I should've read the source code.... That was it.

**Comment by squinkylabs** [comment]
That switch always fools me too! Mostly because I use the sin output for testing other modules, and the "analog" version of sin has some overtones in it.
