### ISSUE TITLE
Using Mixer8 right Expansion input crashes Rack

### ISSUE THREAD

**Issue by Petervos2018** [squinkylabs/SquinkyVCV#77]
On Windows 7 0.6.2c

Connecting anything to the right x input give a crash. 
---------------------------
MinGW Runtime Assertion
---------------------------
Assertion failed!

Program: G:\Zip\Rack EXP\Rack-0.6.2c-2\Rack.exe
File: src/engine.cpp, Line 456

Expression: !(wire2->inputModule == wire->inputModule && wire2->inputId == wire->inputId)
---------------------------
Here is a vcv project , as soon as I want to connect the Nysthi right output with the right input it crashes.

[Squinky Crash.zip](https://github.com/squinkylabs/SquinkyVCV/files/3256650/Squinky.Crash.zip)

**Comment by squinkylabs** [comment]
Got another report not of crashing, but just that it doesn't work. In any case there is clearly a serious bug here.

**Comment by blackearth2014** [comment]
I am getting a major crash as well.

**Comment by terrymullett** [comment]
I'm not getting a crash, but I hear the right expansion input in the left channel at a reduced volume

**Comment by squinkylabs** [comment]
There is a binary for the windows fix posted. Will try to get a mac version posted soon. 1.0.0 version is fixed, of course.

**Comment by squinkylabs** [comment]
mac an win 0.6 builds posted. 1.0.0 plugin manager is good. Closing.
