### ISSUE TITLE
Compile error building v1

### ISSUE THREAD

**Issue by SteveRussell33** [squinkylabs/SquinkyVCV#79]
g++  -std=c++11 -Wsuggest-override -I./dsp/generators -I./dsp/utils -I./dsp/filters -I./dsp/third-party/falco -I./dsp/third-party/kiss_fft130  -I./dsp/third-party/kiss_fft130/tools -I./dsp/third-party/src -I./sqsrc/thread -I./dsp/fft -I./composites -I./sqsrc/noise -I./sqsrc/util -I./sqsrc/clock -I./sqsrc/grammar -I./sqsrc/delay -I./midi/model -I./midi/view -I./midi/controller -I./util -I./src/third-party -I.src/ctrl -D __V1 -fPIC -I../../include -I../../dep/include -MMD -MP -g -O3 -march=nocona -funsafe-math-optimizations -Wall -Wextra -Wno-unused-parameter -DARCH_WIN -D_USE_MATH_DEFINES -fmax-errors=5  -D NDEBUG -c -o build/src/LFNModule.cpp.o src/LFNModule.cpp
In file included from src/LFNModule.cpp:3:
src/Squinky.hpp:4:10: fatal error: component.hpp: No such file or directory
    4 | #include "component.hpp"
      |          ^~~~~~~~~~~~~~~
compilation terminated.
make: *** [../../compile.mk:62: build/src/LFNModule.cpp.o] Error 1

**Comment by Coirt** [comment]
Which version? I think sq7 is the latest.

**Comment by SteveRussell33** [comment]
I used v1; will try sq7

**Comment by squinkylabs** [comment]
v1 is ancient and terrible - I will nuke it.
master is usually good, and set up for v1, but will need to check on it. Should be due for a merge soon.
atm sq7 is the latest, but we hope to keep master up to date.

**Comment by SteveRussell33** [comment]
sq7 worked for me. Thanks.

**Comment by Coirt** [comment]
@squinkylabs master gives out about a few modules that are disabled in sq7.

**Comment by squinkylabs** [comment]
> master gives out about a few modules that are disabled in sq7.

will take a look. tx.
