### ISSUE TITLE
Will SAWS get Polyphonic?

### ISSUE THREAD

**Issue by therealkitman** [squinkylabs/SquinkyVCV#81]
Hi, just a quick one. Am just noodling in rack v1 with SAWS. Will SAWS become polyphonic?
Have been trying to emulate the great sounds from SAWS with other polyphonic VCOs but I just can't get that sound.
Thanks,
Chris.

**Comment by squinkylabs** [comment]
We are (we admit) a little slow to the party with poly. We plan on introducing poly, prioritized based on requests. Saws is a popular request.

**Comment by therealkitman** [comment]
Excellent to hear. In the meantime I'll play with other VCOs (gives me an excuse to explore more :) )
Blamsoft's XFX WAVE is a close contender.
Thanks. 
Closed.

**Comment by therealkitman** [comment]
Just read that SAWS is now polyphonic!!!!!! Brilliant!!! TY!! :)

**Comment by squinkylabs** [comment]
Yes, glad you like it.
