### ISSUE TITLE
I love the new mixer

### ISSUE THREAD

**Issue by blackearth2014** [squinkylabs/SquinkyVCV#84]
I love the new mixers. See attachment. I want to know if it is possible to add stereo ganging from two odd/even faders like 1/2, 3/4 or so on.

<img width="3268" alt="Screen Shot 2019-07-09 at 4 42 48 PM" src="https://user-images.githubusercontent.com/7956901/60921756-46868e80-a269-11e9-92ca-35e0ab0bff23.png">

**Comment by squinkylabs** [comment]
Wow - that's quite a lot of mixer channels! Regarding the ganging - I assume you want to run a stereo signal into (say) intputs 1 and 2, left in 1, right in 2?

**Comment by blackearth2014** [comment]
Yes. I use VCV RACK sometimes for sound design and mini compositions for my
student training videos. Stereo inputs from various sources is a must.

Thanks.

**Comment by blackearth2014** [comment]
If it is not too late, you seem to have space to add a comp/limiter features in the master section for buss compression and summing. Has there been any thoughts in implementing that. I know that we have other compressors & limiters developed by other module makers but that is extra processing that is not always needed. Plus they all have their sound in my opinion.

**Comment by blackearth2014** [comment]
Also can we have the ability to solo more than one channel? This helpful when trying to monitor stereo tracks.

**Comment by squinkylabs** [comment]
> If it is not too late, you seem to have space to add a comp/limiter features in the master section for buss compression...

Unlikely we will make one, but not impossible.

**Comment by squinkylabs** [comment]
> Also can we have the ability to solo more than one channel?

We have already posted that as an enhancement request.

**Comment by blackearth2014** [comment]
Thanks

**Comment by squinkylabs** [comment]
ExTwo module just released adds two stereo channels per instance.
