### ISSUE TITLE
It's very easy to accidentally activate mute or solo while dragging volume in mixers

### ISSUE THREAD

**Issue by squinkylabs** [squinkylabs/SquinkyVCV#87]
In version 1.0.1

**Comment by Coirt** [comment]
#68

**Comment by spectromas** [comment]
Can confirm with the new mixer modules, exactly the same as @Coirt reported.

**Comment by squinkylabs** [comment]
> #68

Yeah, actually a different cause, but same effect ;-(

**Comment by Coirt** [comment]
oh, not the mouse this time?

**Comment by squinkylabs** [comment]
> oh, not the mouse this time?

Oh, yes, it is still mouse button up events hitting a control after you drag off a knob. It's just different controls this time and a different solution.

**Comment by squinkylabs** [comment]
Fixed in 1.0.2, now in the plugin manager.
