### ISSUE TITLE
Form feature request

### ISSUE THREAD

**Issue by jeremywen** [squinkylabs/SquinkyVCV#90]
Can you add polyphonic summing on the inputs?  This would allow me to eliminate the sum module before going to the mixer with each polyphonic voice.

**Comment by squinkylabs** [comment]
Interesting idea. Will for sure consider that.

**Comment by squinkylabs** [comment]
Didn't make it this time, but hopefully next time.

**Comment by squinkylabs** [comment]
Done in 1.0.5.
