### ISSUE TITLE
Minor inconvenience with middle mouse button and Stairway

### ISSUE THREAD

**Issue by Petervos2018** [squinkylabs/SquinkyVCV#91]
I just moved my view with the middle mouse button, and accidentally clicked on the Stairway filter drop-down and this happened : 

![StairwayMiddleMouse](https://user-images.githubusercontent.com/46076474/61578735-37ba9a00-aafb-11e9-938a-4e2ae54b1e41.jpg)

The menu stayed behind while the module went places ;)

**Comment by squinkylabs** [comment]
Yes, this same issue was a major issue with our new mixers (already fixed). Will be fixing this one soon also

**Comment by squinkylabs** [comment]
This is fixed now in version 1.0.4

**Comment by Petervos2018** [comment]
Yes I just saw it, thanks.

Closing.
