### ISSUE TITLE
Mixer-8 mute buttons do not relate visually with Midi-Map

### ISSUE THREAD

**Issue by cyrilfb** [squinkylabs/SquinkyVCV#95]

**Comment by cyrilfb** [comment]
I can map toggle buttons to the mute buttons on Mixer-8 and they do function to turn mute on and off for both master and channel mutes.  But, the yellow squares that indicate they are mapped are not shown and the button color does not change to blue when the midi button is pressed.  I have not checked whether it works with the Solo buttons.
The interface works fine with the dials.  I like this mixer and hope it can be fixed soon.  Perhaps check your other mixers.

**Comment by squinkylabs** [comment]
yes, that is true, they are mapped a little oddly. Have you tried the modular mixers? They are better in most every way - expandable, many more features.... and the mute buttons map like you would expect.

**Comment by cyrilfb** [comment]
Thanks, I had not tried the modular mixers.  All does work as expected there and I do like the expanded/expandable capabilities. I also like that the solo/mute buttons are trigger rather than gate. It would be nice to have VC control of those functions.

**Comment by squinkylabs** [comment]
There is VC control of the gates, isn't there?
